on:
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src
        spec: todoList.spec

    - name: Upload exe file to Release
      uses: actions/upload-artifact@v2
      with:
        name: todoList
        path: src/dist/windows

    # Attach artifact to existing release
    - name: Attach artifact to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: src/dist/windows/todoList.exe
        asset_name: todoList.exe
        asset_content_type: application/octet-stream
